apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odh-notebook-controller-metrics-auth-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odh-notebook-controller-metrics-auth
subjects:
- kind: ServiceAccount
  name: odh-notebook-controller-manager
  namespace: opendatahub
