apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notebook-controller-metrics-monitor
spec:
  selector:
    matchLabels:
      app: notebook-controller
      kustomize.component: notebook-controller
  endpoints:
    - port: nbc-metrics
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: notebook-controller-service.opendatahub.svc
        ca:
          configMap:
            name: openshift-service-ca.crt
            key: service-ca.crt
